// Generated by CoffeeScript 1.9.3
(function() {
  var chrome, url;

  url = require('url');

  chrome = window.chrome = window.chrome || {};

  chrome.extension = {
    getURL: function(path) {
      return url.format({
        protocol: location.protocol,
        slashes: true,
        hostname: location.hostname,
        pathname: path
      });
    }
  };

}).call(this);
