// Generated by CoffeeScript 1.9.3
(function() {
  var EventEmitter, autoUpdater,
    slice = [].slice;

  autoUpdater = process.atomBinding('auto_updater').autoUpdater;

  EventEmitter = require('events').EventEmitter;

  autoUpdater.__proto__ = EventEmitter.prototype;

  autoUpdater.on('update-downloaded-raw', function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    args[3] = new Date(args[3]);
    return this.emit.apply(this, ['update-downloaded'].concat(slice.call(args), [(function(_this) {
      return function() {
        return _this.quitAndInstall();
      };
    })(this)]));
  });

  autoUpdater.quitAndInstall = function() {
    var BrowserWindow, app, i, len, results, win, windows;
    BrowserWindow = require('browser-window');
    windows = BrowserWindow.getAllWindows();
    if (windows.length === 0) {
      this._quitAndInstall();
      return;
    }
    app = require('app');
    app.removeAllListeners('window-all-closed');
    app.once('window-all-closed', this._quitAndInstall.bind(this));
    results = [];
    for (i = 0, len = windows.length; i < len; i++) {
      win = windows[i];
      results.push(win.close());
    }
    return results;
  };

  module.exports = autoUpdater;

}).call(this);
