// Generated by CoffeeScript 1.9.3
(function() {
  var EventEmitter, Tray, bindings;

  EventEmitter = require('events').EventEmitter;

  bindings = process.atomBinding('tray');

  Tray = bindings.Tray;

  Tray.prototype.__proto__ = EventEmitter.prototype;

  Tray.prototype.setContextMenu = function(menu) {
    this._setContextMenu(menu);
    return this.menu = menu;
  };

  Tray.prototype.popContextMenu = Tray.prototype.popUpContextMenu;

  module.exports = Tray;

}).call(this);
