// Generated by CoffeeScript 1.9.3
(function() {
  if (process.platform === 'linux' && process.type === 'renderer') {
    module.exports = require('remote').require('clipboard');
  } else {
    module.exports = process.atomBinding('clipboard');
  }

}).call(this);
