// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = process.atomBinding('shell');

  if (process.platform === 'win32' && process.type === 'renderer') {
    module.exports.showItemInFolder = require('remote').process.atomBinding('shell').showItemInFolder;
  }

}).call(this);
